<a href="https://colab.research.google.com/github/dkuzzmin/DI-Bootcamp/blob/main/Week6/Day1/W6_D1_XC_XP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [3]:
#1
array = np.array(range(0,10,1))
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#2
a = [3.14, 2.17, 0, 1, 2]
array = np.array(a, dtype=int)
array

array([3, 2, 0, 1, 2])

In [3]:
#3
array = np.array([[1,2,3], [4,5,6], [7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
#4
array = np.random.rand(1, 20).reshape(4,5)
array

array([[0.18604614, 0.51865768, 0.66708474, 0.3737934 , 0.36177429],
       [0.96993582, 0.06987601, 0.23926294, 0.41459043, 0.14902931],
       [0.16941655, 0.16675539, 0.76905735, 0.75076958, 0.82343622],
       [0.24803862, 0.28803315, 0.14705977, 0.29209236, 0.0942754 ]])

In [24]:
#5
sub_row = array[1, :]
sub_row

array([0.96993582, 0.06987601, 0.23926294, 0.41459043, 0.14902931])

In [31]:
#6
array = np.array([1,2,3,4,5,6,7,8,9,10])
print(array)
array = array[::-1]
array

[ 1  2  3  4  5  6  7  8  9 10]


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [33]:
#7
array = np.eye(4)
array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
#8
array = np.array([1,3,5,9,8,7,4,3,2])
array.sum()

42

In [44]:
array.mean()

4.666666666666667

In [45]:
print(f'Sum: {array.sum()}, Average: {array.mean()}')

Sum: 42, Average: 4.666666666666667


In [41]:
#9
array = np.arange(1, 21)
array
array = array.reshape(4,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [50]:
#10

array = np.arange(1, 11)
odd = array[::2]
odd


array([1, 3, 5, 7, 9])